version: 0.2

env:
 variables:
   APP_NAME: "EBDemo"
   APP_ENV: "prod"
   APP_DEBUG: "true"
   LOG_CHANNEL: "stack"
 parameter-store:
   APP_KEY: "/CodeBuild/APP_KEY"

phases:
 install:
   commands:
     - |
         export DEBIAN_FRONTEND=noninteractive

         #Install php7.1
         apt-get update
         apt-get install -y  software-properties-common
         LC_ALL=C.UTF-8 add-apt-repository -y ppa:ondrej/php
         apt-get update

         # Install PHP
         apt-get install -y php7.1
         apt-get install -y php7.1-ldap
         apt-get install -y php7.1-xml
         apt-get install -y php7.1-xmlrpc
         apt-get install -y php7.1-zip
         apt-get install -y php7.1-mysql
         apt-get install -y php7.1-mbstring
         apt-get install -y php7.1-mcrypt
         apt-get install -y php7.1-gd
         apt-get install -y php7.1-readline
         apt-get install -y php7.1-opcache
         apt-get install -y php7.1-xdebug
         apt-get install -y php7.1-dom
         apt-get install -y php-xdebug
         apt-get install -y php7.1-curl
         unzip

         #Enable xdebug - phpunit uses this for code coverage
         phpenmod xdebug

         #Install composer
         php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
         php composer-setup.php ;
         php -r "unlink('composer-setup.php');" ;
         mv composer.phar /usr/local/bin/composer

 pre_build:
   commands:
     - echo Pre_Build started on `date`
     - printenv > .env

 build:
   commands:
     - echo Build started on `date`
     - echo Installing composer deps
     - composer install --no-progress --no-suggest

 post_build:
   commands:
     - echo Build completed on `date`

artifacts:
 files:
   - '**/*'